Weets api sign up
wolox-training/jb-express-js pull request #3
Opened 2021-11-04 14:49 UTC by javerBenavidez

## Summary

Add new endpoint to manage sign up of new users. Validate and save users information.

## Known Issues

None

## Trello Card

https://trello.com/c/J74OtWxW/35-sign-up

2021-11-04 21:41 UTC, martinremis requested changes
Well done, just some comments.

2021-11-04 21:41 UTC, martinremis commented on app/controllers/users.js
> +    throw databaseError(e.message);
Do not throw database errors messages. It may contain sensitive information (user info or internal server info).

2021-11-04 21:41 UTC, martinremis commented on app/middlewares/validator.js
> +    const domains = ['wolox.com.ar', 'wolox.co', 'wolox.cl'];
This may be in a `constants` file

2021-11-04 22:13 UTC, javerBenavidez commented
please review again

2021-11-05 13:45 UTC, martinremis approved these changes

2021-11-05 13:45 UTC, martinremis commented on app/controllers/users.js
> +    next(databaseError(DB_CONNECTION));
Good change, I forgot to said you should use `next` here instead of throw 😛

2021-11-05 14:26 UTC, merged